# Conclusions

## Summary

<p> In my dissertation I have applied, adapted and extended the forward selection procedure under the marginality assumption first proposed by \cite{hao2014interaction}. This procedure is able to reduce the search space substantially by making some reasonable assumptions about the data and underlying biological structure. These assumptions can be relaxed a little to broaden the scope of the search space if desired. The procedure has been applied in both simulated and real datasets in all areas of study. There are many advantages to using such a procedure with some being it is a computationally efficient way for high dimensional data situations that arise from high throughput data, especially when considering epistasis between gene markers or other type of interaction effects in the model.  The search space is guided based off of commonly used principles in model selection that are relevant in real world situations. It is able to perform a GWAS with included epistatic interactions a fairly quick manner.</p>

<p> The ability to relax these assumptions leads to a widened search space but may decrease the speed of the algorithm.  This will make the search more comprehensive and able to pick up on effects that may have been missed with stricter assumptions. One nice use for the procedure is the ability to screen for complex scenarios that would be hard to find in a lab setting otherwise. The screening lends itself to find previously undiscovered effects but with the flexibility of the initial model, false positive rates could be a concern and need to be taken into consideration. Adjustment to the significance level and the model selection criteria have been made to account for this. This would still need to be followed up by independently checking with other datasets and/or lab verification techniques.</p>

### HighDeQTL

<p> In [Chapter 02](#highdeqtl) the iFORM procedure was introduced and explored. It showed many desirable properties for high dimensional data analysis. Simulation studies were performed to assess the properties and compare across other models. After simulations were conducted a real world application was conducted on gene expression data and conducting a GWAS to find eQTLs for the different genes. Using all markers in a single model as well as the inclusion of the possibility to include epistatic effects as eQTLs gave a novel take on the reanalysis of the C Elegans dataset. As we have seen there are many advantages to the approach but one limiting question presented was that the restriction on epistatic effects may have been too restrictive. Using the strong heredity principle may miss some interactions that could occur between markers that have not yet been selected. Also only considering interactions with markers at two loci instead of higher orders could be limiting the search to fully explain the expression profile.</p>

### Higher Order Epistasis

<p> In [Chapter 03](#highorder) higher order epistasis was focused on the help explain a larger proportion of the phenotypic variation. Extending the iFORM procedure to open up the possibility of higher order epistasis is pivotal in understanding complex traits. More support is coming out that phenotypes that are controlled by a multitude of genetic and epigenetic effects potential could come from effects involving three or more loci (\cite{taylor2014genetic}). Given that this is the case the procedure was extended and simulation studies were conducted to see the affect on the properties of the procedure. Different levels of heredity and different orders of interactions were also assessed.  Other types of interaction models were also presented for comparison purposes. The iFORM procedure performed well in the simulation studies and appeared to capture the relevant information from the underlying models.  A real world application was then presented on a growth parameter of Mei trees. The difference in running the procedure with the possibility of finding higher order epistasis allowed for a much greater proportion the variance to be explained by the markers.  This was favorable for the inclusion of higher order effects and showed promise for the model. The phenotype was a static growth parameter, which was the rate at which the trees grew for each individual observation. The growth was measured over time and then a growth curve was fit for each tree. This was then used for the phenotype. This was a good approach but it misses the repeated measures and possibly other information that may have been present throughout the growth process. Since this is the case a functional phenotype was considered to help capture all relevant information. </p>

### iForm Functional Mapping

<p> In [Chapter 04](#iformfunc) functional components were also considered for the selection procedure. This increases the computational complexity of the model and therefore decreases some efficiency gains previously seen but is necessary to capture all information. Using biologically relevant information to guide the fitting of the model to a functional curve will help improve the efficiency and relevance. Initially well established growth equations were considered as a baseline for the underlying structure. The procedure then performs a GWAS level analysis with considering epistatic interactions throughout the process. The selection of the markers as possible genetic and epigenetic effects follows in a similar fashion as the iForm procedure. Additional aspects had to be accounted for the functional response and growth curve.  Again simulation studies were performed and a real world application was conducted. A reanalysis of the full Mei tree dataset used in chapter 3 was explored. Including the functional valued phenotype gave new insight into the genetic control. </p>

## Discussion

<p> The selection procedures proposed attempt to address problems that are complex and have many moving parts to the procedure. Using a flexible model is very helpful to fulfill such requirements but this could lend itself to be prone to over fitting at times if not well controlled.  Being aware of this factor is part of interpreting the model a researcher would need to be aware of. Using stricter selection criteria and corrections to multiple testing for significance is extremely important. The main purpose is to use as a screening to guide future research while considering the possibilities of epistatic effects and accounting for the entire genetic architecture at one time. The importance of such a procedure could be used to help guide research and also find new discoveries into complex, multi-loci traits that would be extremely difficult to find in just a lab setting alone.</p>

<p> There are many attractive properties that the iFORM procedure posses. It is computationally efficient given the large and growing predictor space it uses.  Along with the computational advantages, the selection procedures proposed have sure screening properties. This indicates that all the important effects in the true model will be selected with probability tending to one. It also only includes a small proportion of effects based off of a designated criteria that can be set. This will help with interpretability of the final output as well as controlling for the possibility of overfitting the data. There is still much that can be extended and explored by using this type of selection procedure on a variety of settings and/or phenotypes.</p>

## Future Steps

### Aim 1

<p> Incorporating other curves for the mean response curve could help extend and relate to other areas of biology that follow a functional trait. There are also other types of orthogonal polynomials that could be explored as well. Using others polynomials would allow for other fits to the data that may be more applicable in other scenarios. Also using other basis functions in general could open up opportunities for other areas of application. There are many non-linear functions that could be used besides a polynomial fit that may also explain the underlying genetic effects over time for other situations. </p>

### Aim 2

<p> Other interesting areas would be to consider different levels of interactions with other omics data. The gene-gene interactions considered are only a portion of the picture and this type of modeling could also handle complex levels of interactions that occur in a biological system. One area that I am particularly interested in applying it to would be in methylation and its interaction with gene expression. This level of interaction is very important and a selection procedure like the one proposed could help screen and generate possible effects for hypotheses to continue to look into. This does not have to be restricted to just within the biological system under study. It would also apply in gene-environment interactions. Environmental factors are important areas that could vastly impact the development of a phenotype. Having the interaction with environmental factors could open up further avenues that able to previously be explored.</p>

### Aim 3

<p> Statistical areas that could as be considered to extend the model would be to include multivariate responses to the system. For example having gene and protein expression being a bivariate response and to see how genetic markers and epistasis between the markers would better predict this scenario.  It could take the correlation between the protein and expression response variables into account. Other statistical considerations would be to extend selection criteria to help further reduce the possibility of false positives being selected given a growing dataset like the one that occurs while dynamically including interaction effects throughout the selection. Making the model even more computational efficient would always be beneficial as well. The faster a model can accurately run the more likely a researcher will be to use it. It will also help process all the high throughput data that is being constantly developed.</p>

### Closing Remarks

<p> Continuing on, my aim would be to work with datasets of high dimensional scale and incorporate the types of statistical methods mentioned and machine learning techniques to aid in analysis. The results could help gain larger insights into the genomic/epigenetic architecture of biological systems. On top of the importance of a functional component to the phenotype, considering other types of multivariate responses would be interesting to study in context of such a system. Integrating different level of omics data and the challenges that arise with such complicated and large datasets has interested me throughout my work. Translating such a complex system into usable information that can be shared in order to prevent and fight disease would be ideal research. This type of research would need both methodological development as well as application of existing statistical and machine/deep learning techniques to handle the magnitude of the problem.</p>
